# Generated by Django 5.2 on 2026-09-13 08:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
